use_frameworks!
install! 'cocoapods', :generate_multiple_pod_projects => true
inhibit_all_warnings!

target 'Stem_Example' do
  pod 'Stem', :path => '../'
  pod 'SnapKit'
  pod 'Then'
  pod 'BLFoundation'
  pod 'SVProgressHUD'
  
  target 'Stem_Tests' do
    inherit! :search_paths
    pod 'BLFoundation'
    pod 'Stem', :path => '../'

  end
end
