source 'https://cdn.cocoapods.org/'

use_frameworks!
install! 'cocoapods', :generate_multiple_pod_projects => true
inhibit_all_warnings!

target 'Stem_Example' do
  pod 'Stem', :path => '../'
  pod 'SnapKit'
  pod 'Then'
  pod 'SVProgressHUD'
  pod 'SwiftLint'
  pod 'Stuart', :git => 'git@github.com:linhay/Stuart.git',:branch => '0.1.0'
  
  target 'Stem_Tests' do
    inherit! :search_paths
    pod 'Stem', :path => '../'

  end
end

target 'stem_macos_example' do
  pod 'Stem/Foundation/Custom', :path => '../'
  pod 'SnapKit'
  pod 'Then'
  pod 'SwiftLint'
end


