language: swift

osx_image:
- xcode10.1
- xcode10.2


before_install:
- gem update --system
- gem install bundler
- gem install cocoapods -v 1.6.2
- pod repo update
- pod install --project-directory=Example


cache: cocoapods
podfile: Example/Podfile

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_WORKSPACE=Example/Stem.xcworkspace
  matrix:
    - SCHEME="Stem-Example"

script:
  - set -o pipefail
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Debug clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - pod lib lint --allow-warnings

after_success:
  - sleep 3
