# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode11

env:
  - ACTION=test  PLATFORM=Mac     DESTINATION='platform=macOS'
  - ACTION=test  PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone 6S'
  - ACTION=test  PLATFORM=tvOS    DESTINATION='platform=tvOS Simulator,name=Apple TV 4K (at 1080p)'

script:
  - set -o pipefail && xcodebuild -scheme Stem-Example -destination "$DESTINATION" $ACTION | xcpretty

after_success:
- sleep 3
